WaterHouseUsingMVC/Models/Order.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using System.Linq;
using System.Web;


namespace WaterHouseUsingMVC.Models
{

    [Table("OrderList")]
    public class Order
    {
        [Key]
        public int ORDERNUMBER { get; set; }
        [Required]
        public string FIRSTNAME { get; set; }
        public string MIDDLENAME { get; set; }
        [Required]
        public string LASTNAME { get; set; }
        [Required]
        public string MOBILENO { get; set; }
        [Required]
        public string ADDRESS { get; set; }
        public int QTYICEBOTTLE { get; set; }
        public int QTYBTBOTTLE { get; set; }
        public int QTYPOUCH { get; set; }
        public int ROOTID { get; set; }

    }
}

WaterHouseUsingMVC/Models/OrderListDBContext.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Data.Entity;

namespace WaterHouseUsingMVC.Models
{
    public class OrderListDBContext:DbContext
    {
        public DbSet<Order> OrderList { get; set; }
        public DbSet<Root> RootList { get; set; }
    }
}

WaterHouseUsingMVC/Models/Root.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using System.Linq;
using System.Web;

namespace WaterHouseUsingMVC.Models
{
    [Table("RootList")]
    public class Root
    {
        [Key]
        public int ROOT_ID { get; set; }
        public string STATION { get; set; }
        public List<Order> OrderList { get; set; }
    }
}

WaterHouseUsingMVC/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace WaterHouseUsingMVC.Controllers
{
    public class HomeController : Controller
    {
        //
        // GET: /Home/

        public ActionResult Index()
        {
            ViewBag.Products = new List<string>() { 
                "Aqua Pouch",
                "BT Jug",
                "Cool Jug"
             };
            return View();
        }

    }
}

WaterHouseUsingMVC/Controllers/OrderDetailsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using WaterHouseUsingMVC.Models;

namespace WaterHouseUsingMVC.Controllers
{
    public class OrderDetailsController : Controller
    {
        //
        // GET: /OrderListDetails/

        public ActionResult Details(int id)
        {
            Order order = new Order()
            {
                ORDERNUMBER = 1001,
                FIRSTNAME = "Mukesh",
                MIDDLENAME = "G",
                LASTNAME = "Methaniya",
                MOBILENO = "9998186874",
                ADDRESS = "Bharada",
                QTYBTBOTTLE = 5,
                QTYPOUCH = 4,
                QTYICEBOTTLE = 10,
                ROOTID=101
            };
            OrderListDBContext orderList = new OrderListDBContext();
            if (orderList.OrderList.Count() == 0)
            {
                orderList.OrderList.Add(order);
                orderList.SaveChanges();
                id = 0;
            }
            else
            {

                order = orderList.OrderList.Single(x => x.ORDERNUMBER == id);
            }
            return View(order);
        }

        public ActionResult Orders(int rootId)
        {
            OrderListDBContext orderList = new OrderListDBContext();
            return View(orderList.OrderList.ToList());
        }

       
    }
}

WaterHouseUsingMVC/Controllers/OrderTableController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

using WaterHouseUsingMVC.Models;

namespace WaterHouseUsingMVC.Controllers
{
    public class OrderTableController : Controller
    {
        //
        // GET: /OrderTable/

        public ActionResult Index()
        {
            //OrderListDBContext orderList = new OrderListDBContext();
            WaterHouseBusinessLayer.OrderBusinessLayer bl = new WaterHouseBusinessLayer.OrderBusinessLayer();

            return View(bl.OrderList.ToList());

        }
        [HttpGet]
        public ActionResult Create()
        {
            return View();
        }

        //[HttpPost]
        //public ActionResult Create(FormCollection collection)
        //{
        //    Order order = new Order();
        //    order.ORDERNUMBER =Convert.ToInt32(collection["ORDERNUMBER"]);
        //    order.FIRSTNAME = collection["FIRSTNAME"];

        //    order.MIDDLENAME = collection["MIDDLENAME"];
        //    order.LASTNAME = collection["LASTNAME"];
        //    order.ROOTID = Convert.ToInt32(collection["ROOTID"]);
        //    OrderListDBContext orderList = new OrderListDBContext();
        //    orderList.OrderList.Add(order);
        //    orderList.SaveChanges();

        //   return RedirectToAction("Index");

        //   // return View();
        //}

        [HttpPost]
        public ActionResult Create(WaterHouseBusinessLayer.Order order)
        {
            if (ModelState.IsValid)
            {
             //   OrderListDBContext orderList = new OrderListDBContext();
            //    orderList.OrderList.Add(order);
            //    orderList.SaveChanges();
                WaterHouseBusinessLayer.OrderBusinessLayer bl = new WaterHouseBusinessLayer.OrderBusinessLayer();
                bl.AddOrder(order);
                return RedirectToAction("Index");
            }
            return View();
        }

        [HttpGet]
        public ActionResult Edit(int id)
        {
           // OrderListDBContext orderList = new OrderListDBContext();
            WaterHouseBusinessLayer.OrderBusinessLayer bl = new WaterHouseBusinessLayer.OrderBusinessLayer();
            WaterHouseBusinessLayer.Order order = bl.OrderList.Single(x => x.ORDERNUMBER == id);
            return View(order);
        }

        [HttpPost]
        public ActionResult Edit(Order order)
        {
            if(ModelState.IsValid)
            {
            OrderListDBContext orderList = new OrderListDBContext();
            Order orderDB = orderList.OrderList.Single(x => x.ORDERNUMBER == order.ORDERNUMBER);
            orderDB.FIRSTNAME = order.FIRSTNAME;
            orderDB.MIDDLENAME = order.MIDDLENAME;
            orderDB.LASTNAME = order.LASTNAME;
            orderDB.MOBILENO = order.MOBILENO;
            orderDB.ADDRESS = order.ADDRESS;
            orderDB.QTYBTBOTTLE = order.QTYBTBOTTLE;
            orderDB.QTYICEBOTTLE = order.QTYICEBOTTLE;
            orderDB.QTYPOUCH = order.QTYPOUCH;
            orderDB.ROOTID = order.ROOTID;
            orderList.SaveChanges();
            return RedirectToAction("Index");
            }

            return View(order);
        }
    }
}

WaterHouseUsingMVC/Controllers/RootDetailsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using WaterHouseUsingMVC.Models;

namespace WaterHouseUsingMVC.Controllers
{
    public class RootDetailsController : Controller
    {
        //
        // GET: /RootDetails/


        public ActionResult Details(int rootId)
        {
            Root root = new Root()
            {
              ROOT_ID=1001,
              STATION="THALA-BHARADA"

            };
            OrderListDBContext orderList = new OrderListDBContext();
            if (orderList.RootList.Count() == 0)
            {
                orderList.RootList.Add(root);
                orderList.SaveChanges();
                rootId = 1001;
            }
            else
            {

                root = orderList.RootList.Single(x => x.ROOT_ID == rootId);
            }
            return View(root);
        }

        public ActionResult Roots()
        {
            OrderListDBContext orderList = new OrderListDBContext();
            return View(orderList.RootList.ToList());
        }

    }
}

WaterHouseUsingMVC/Views/Home/Index.cshtml
@{
    ViewBag.Title = "Shree Hari mineral water";
}

<h2>Products</h2>
<ul>
    @foreach(string product in ViewBag.Products)
    {
    <li> @product</li>
    }
</ul>

WaterHouseUsingMVC/Views/OrderDetails/Details.cshtml
@model WaterHouseUsingMVC.Models.Order

@{
    ViewBag.Title = "Order Details";
}

<h2>Order Details</h2>

<table>
    <tr>
        <td>Name</td>
        <td>@Model.FIRSTNAME</td>
    </tr>
    <tr>
        <td>Mobile Number</td>
        <td>@Model.MOBILENO</td>
    </tr>
    <tr>
        <td>Pouch Qty </td>
        <td>@Model.QTYPOUCH</td>
    </tr>
    <tr>
        <td>@Html.ActionLink("Back To Order List", "Orders", "OrderDetails", new  { rootId=@Model.ROOTID },null)</td>
    </tr>
</table>

WaterHouseUsingMVC/Views/OrderDetails/Orders.cshtml
@using WaterHouseUsingMVC.Models;
@model List<WaterHouseUsingMVC.Models.Order>

@{
    ViewBag.Title = "Orders";
}

<h2>Orders</h2>
<table>
    @foreach(Order order in Model)
    {
    <tr>
       
       <td> @Html.ActionLink(order.FIRSTNAME,"Details","OrderDetails", new { id = order.ORDERNUMBER },null);</td>

    </tr>
    }

    <tr>
        <td>@Html.ActionLink("Back To Root", "Details", "RootDetails", new  { rootId=@Model[0].ROOTID },null)</td>
    </tr>
</table>

WaterHouseUsingMVC/Views/OrderTable/Create.cshtml
@model WaterHouseBusinessLayer.Order

@{
    ViewBag.Title = "Create";
}

<h2>Create</h2>

@using (Html.BeginForm()) {
    @Html.AntiForgeryToken()
    @Html.ValidationSummary(true)

    <fieldset>
        <legend>Order</legend>

        <div class="editor-label">
            @Html.LabelFor(model => model.FIRSTNAME)
        </div>
        <div class="editor-field">
            @Html.EditorFor(model => model.FIRSTNAME)
            @Html.ValidationMessageFor(model => model.FIRSTNAME)
        </div>

        <div class="editor-label">
            @Html.LabelFor(model => model.MIDDLENAME)
        </div>
        <div class="editor-field">
            @Html.EditorFor(model => model.MIDDLENAME)
            @Html.ValidationMessageFor(model => model.MIDDLENAME)
        </div>

        <div class="editor-label">
            @Html.LabelFor(model => model.LASTNAME)
        </div>
        <div class="editor-field">
            @Html.EditorFor(model => model.LASTNAME)
            @Html.ValidationMessageFor(model => model.LASTNAME)
        </div>

        <div class="editor-label">
            @Html.LabelFor(model => model.MOBILENO)
        </div>
        <div class="editor-field">
            @Html.EditorFor(model => model.MOBILENO)
            @Html.ValidationMessageFor(model => model.MOBILENO)
        </div>

        <div class="editor-label">
            @Html.LabelFor(model => model.ADDRESS)
        </div>
        <div class="editor-field">
            @Html.EditorFor(model => model.ADDRESS)
            @Html.ValidationMessageFor(model => model.ADDRESS)
        </div>

        <div class="editor-label">
            @Html.LabelFor(model => model.QTYICEBOTTLE)
        </div>
        <div class="editor-field">
            @Html.EditorFor(model => model.QTYICEBOTTLE)
            @Html.ValidationMessageFor(model => model.QTYICEBOTTLE)
        </div>

        <div class="editor-label">
            @Html.LabelFor(model => model.QTYBTBOTTLE)
        </div>
        <div class="editor-field">
            @Html.EditorFor(model => model.QTYBTBOTTLE)
            @Html.ValidationMessageFor(model => model.QTYBTBOTTLE)
        </div>

        <div class="editor-label">
            @Html.LabelFor(model => model.QTYPOUCH)
        </div>
        <div class="editor-field">
            @Html.EditorFor(model => model.QTYPOUCH)
            @Html.ValidationMessageFor(model => model.QTYPOUCH)
        </div>

        <div class="editor-label">
            @Html.LabelFor(model => model.ROOTID)
        </div>
        <div class="editor-field">
            @Html.EditorFor(model => model.ROOTID)
            @Html.ValidationMessageFor(model => model.ROOTID)
        </div>

        <p>
            <input type="submit" value="Create" />
        </p>
    </fieldset>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

WaterHouseUsingMVC/Views/OrderTable/Edit.cshtml
@model WaterHouseBusinessLayer.Order

@{
    ViewBag.Title = "Edit";
}

<h2>Edit</h2>

@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    @Html.ValidationSummary(true)

    <fieldset>
        <legend>Order</legend>

        @Html.HiddenFor(model => model.ORDERNUMBER)

        <div style="font-family: Arial">
            <div class="editor-label">
                @Html.LabelFor(model => model.FIRSTNAME)
            </div>
            <div class="editor-field">
                @Html.EditorFor(model => model.FIRSTNAME)
                @Html.ValidationMessageFor(model => model.FIRSTNAME)
            </div>

            <div class="editor-label">
                @Html.LabelFor(model => model.MIDDLENAME)
            </div>
            <div class="editor-field">
                @Html.EditorFor(model => model.MIDDLENAME)
                @Html.ValidationMessageFor(model => model.MIDDLENAME)
            </div>

            <div class="editor-label">
                @Html.LabelFor(model => model.LASTNAME)
            </div>
            <div class="editor-field">
                @Html.EditorFor(model => model.LASTNAME)
                @Html.ValidationMessageFor(model => model.LASTNAME)
            </div>

            <div class="editor-label">
                @Html.LabelFor(model => model.MOBILENO)
            </div>
            <div class="editor-field">
                @Html.EditorFor(model => model.MOBILENO)
                @Html.ValidationMessageFor(model => model.MOBILENO)
            </div>

            <div class="editor-label">
                @Html.LabelFor(model => model.ADDRESS)
            </div>
            <div class="editor-field">
                @Html.EditorFor(model => model.ADDRESS)
                @Html.ValidationMessageFor(model => model.ADDRESS)
            </div>

            <div class="editor-label">
                @Html.LabelFor(model => model.QTYICEBOTTLE)
            </div>
            <div class="editor-field">
                @Html.EditorFor(model => model.QTYICEBOTTLE)
                @Html.ValidationMessageFor(model => model.QTYICEBOTTLE)
            </div>

            <div class="editor-label">
                @Html.LabelFor(model => model.QTYBTBOTTLE)
            </div>
            <div class="editor-field">
                @Html.EditorFor(model => model.QTYBTBOTTLE)
                @Html.ValidationMessageFor(model => model.QTYBTBOTTLE)
            </div>

            <div class="editor-label">
                @Html.LabelFor(model => model.QTYPOUCH)
            </div>
            <div class="editor-field">
                @Html.EditorFor(model => model.QTYPOUCH)
                @Html.ValidationMessageFor(model => model.QTYPOUCH)
            </div>

            <div class="editor-label">
                @Html.LabelFor(model => model.ROOTID)
            </div>
            <div class="editor-field">
                @Html.EditorFor(model => model.ROOTID)
                @Html.ValidationMessageFor(model => model.ROOTID)
            </div>
        </div>
        <p>
            <input type="submit" value="Save" />
        </p>
    </fieldset>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

WaterHouseUsingMVC/Views/OrderTable/Index.cshtml
@model IEnumerable<WaterHouseBusinessLayer.Order>

@{
    ViewBag.Title = "Index";
}

<h2>Index</h2>

<p>
    @Html.ActionLink("Create New", "Create")
</p>
<table border="1">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.FIRSTNAME)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.MIDDLENAME)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.LASTNAME)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.MOBILENO)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.ADDRESS)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.QTYICEBOTTLE)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.QTYBTBOTTLE)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.QTYPOUCH)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.ROOTID)
        </th>
        <th>Action</th>
    </tr>

@foreach (var item in Model) {
    <tr>
        <td>
            @Html.DisplayFor(modelItem => item.FIRSTNAME)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.MIDDLENAME)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.LASTNAME)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.MOBILENO)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.ADDRESS)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.QTYICEBOTTLE)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.QTYBTBOTTLE)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.QTYPOUCH)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.ROOTID)
        </td>
        <td>
            @Html.ActionLink("Edit", "Edit", new { id=item.ORDERNUMBER }) |
            @Html.ActionLink("Details", "Details", new { id=item.ORDERNUMBER }) |
            @Html.ActionLink("Delete", "Delete", new { id=item.ORDERNUMBER })
        </td>
    </tr>
}

</table>

WaterHouseUsingMVC/Views/RootDetails/Details.cshtml
@model WaterHouseUsingMVC.Models.Root

@{
    ViewBag.Title = "RootDetails";
}

<h2>RootDetails</h2>
<table>
    <tr>
        <td>Root Name</td>

        <td>@Html.ActionLink(@Model.ROOT_ID.ToString(), "Orders", "OrderDetails", new {rootId=Model.ROOT_ID },null);</td>
    </tr>
    <tr>
        <td>Root Details</td>
        <td>@Model.STATION</td>
    </tr>

    @*   <tr>
        <td>@Html.ActionLink("Back To Order List","Orders","OrderDetails")</td>
    </tr>*@
</table>

WaterHouseUsingMVC/Views/RootDetails/Roots.cshtml
@using WaterHouseUsingMVC.Models;
@model List<WaterHouseUsingMVC.Models.Root>

@{
    ViewBag.Title = "Roots";
}

<h2>Roots</h2>
<table>
    @foreach(Root route in Model)
    {
    <tr>
        <td>Root Name</td>
    
        <td>@Html.ActionLink(route.STATION, "Details", "RootDetails", new  { rootId = route.ROOT_ID }, null);   </td>
    </tr> 
       
    }

</table>